### ISSUE TITLE
Make it more friendly to md table

### ISSUE THREAD

**Issue by Steven-AA** [ijgnd/anki21__PFP_table#1]
if I copy a table from a md document, I have to delete the second line and delete "|" from the beginning and the end of each line,
turn this:
```
|A|B|C|
|--|--|--|
|D|E|F|
```
into this
```
A|B|C
D|E|F
```
Can you make this easier?
Thanks a lot.

**Comment by ijgnd** [comment]
sorry for answering so late. I didn't get a notification because I wasn't properly subscribed to this repo.

Your idea sounds very useful.

I changed the code. I also did some other changes. Before I publish this to Ankiweb would you try it out and report if it works as expected and if you run into different problems? 

The new code is at https://github.com/ijgnd/anki__PFP_table/releases/download/0.1/add_table__21.zip

Delete the contents of the folder for the add_table_addon (it should be named `1237621971` and is in the folder addons 21 in your anki folder). Then put in the contents of the zip file.

**Comment by Steven-AA** [comment]
It works great. Thanks a lot.

**Comment by ijgnd** [comment]
I had some problems with the version from December because trailing spaces can create additional columns.

I just made some changes and uploaded a new version (with support for leading/trailing "|") to https://ankiweb.net/shared/info/1237621971 . If you find any problems with it let me know.
