### ISSUE TITLE
Support newer Anki versions

### ISSUE THREAD

**Issue by elvis-sik** [ijgnd/anki21__PFP_table#12]
Would it be difficult to support newer versions of Anki with this add-on? I only used it a couple of times and would continue to use it infrequently, but I think it provides very useful functionality.

Thank you.

**Comment by ijgnd** [comment]
it should work with the latest released versions and the beta for 2.1.41.

On ankiweb it's actually listed as "2.1.28 **+**" so that you install it in the latest versions. 

I update the compatibility info whenever I upload a new version. Updating this info with every release for my 70+ add-on would be too time consuming. Also with 70+ add-on it's too time consuming to test each add-on with every new release.

What I do is not uncommon, e.g. the popular add-ons  "Symbols As You Type" or "The KING of Button Add-ons" are still listed as "2.1.24+".

If you still have a problem with my add-on let me know.

**Comment by elvis-sik** [comment]
Thank you for the quick answer! **tl;dr**: you're correct and it works :)

When I posted the issue, I had just upgraded Anki from an older 2.1 version to 2.1.40 and this addon was auto-disabled with a message saying it requires Anki <= 2.1.23.

After seeing your answer here, I used `Get add on` pasting the code from Ankiweb (as if I was installing this addon the first time) and it worked. I don't know if this known/expected Anki behavior, but I had no idea I had to do this.

**Comment by ijgnd** [comment]
I guess you updated from an older verison <= 2.1.23?

On Ankiweb I can upload different versions of add-ons for different anki versions.

For add tabe I have:

    2.1.0-2.1.23 (updated 2020-07-25)
    2.1.24-2.1.28+ (updated 2020-07-25)

So you had the old versions installed which doesn't work with 2.1.40. If you had checked for updates for add-ons (there's a button on the top right of the add-on dialog in Anki) you would have been offered an update.

Anki's behavior is not perfect. 

Anki automatically checks for add-on updates once a day. Maybe it should also check on the first start after updating to a new anki version to avoid such problems. I don't think it currently does it. Maybe you could suggest this to the anki creator in the official forum at https://forums.ankiweb.net/.
